version: 2
jobs:
  build:
    docker:
        - image: circleci/golang:1.13
    steps:
        - checkout
        - run:
            name: Build GEL plugin
            command: make
        - store_artifacts:
            path: dist
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
