version: 2
jobs:
  build:
    docker:
        - image: srclosson/grafana-plugin-ci:latest
    steps:
        - checkout
        - run:
            name: Test GEL plugin
            command: mage coverage
        - run:
            name: Build GEL plugin
            command: |
              mage clean
              mage copyArtifacts
              mage buildAll
        - store_artifacts:
            path: dist
        - store_artifacts:
            path: coverage
workflows:
  version: 2
  gel_build:
    jobs:
      - build
