version: 2
jobs:
  build:
    docker:
        - image: circleci/golang:1.13
    steps:
        - checkout
        - run:
            name: Test GEL plugin
            command: make test
        - run:
            name: Build GEL plugin
            command: make
        - store_artifacts:
            path: dist
        - store_artifacts:
            path: coverage
workflows:
  version: 2
  gel_build:
    jobs:
      - build
